//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images/start.png")]
        public string StateButtonInitialValue {
            get {
                return ((string)(this["StateButtonInitialValue"]));
            }
            set {
                this["StateButtonInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BestScoreInitialValue {
            get {
                return ((int)(this["BestScoreInitialValue"]));
            }
            set {
                this["BestScoreInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScoreInitialValue {
            get {
                return ((int)(this["ScoreInitialValue"]));
            }
            set {
                this["ScoreInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public string TimerInitialValue {
            get {
                return ((string)(this["TimerInitialValue"]));
            }
            set {
                this["TimerInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images/pause.png")]
        public string StateButtonPauseValue {
            get {
                return ((string)(this["StateButtonPauseValue"]));
            }
            set {
                this["StateButtonPauseValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press to start the game!")]
        public string StateButtonToolTipInitialValue {
            get {
                return ((string)(this["StateButtonToolTipInitialValue"]));
            }
            set {
                this["StateButtonToolTipInitialValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press to pause the game!")]
        public string StateButtonToolTipPausedValue {
            get {
                return ((string)(this["StateButtonToolTipPausedValue"]));
            }
            set {
                this["StateButtonToolTipPausedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press to continue the game!")]
        public string StateButtonToolTipContinueValue {
            get {
                return ((string)(this["StateButtonToolTipContinueValue"]));
            }
            set {
                this["StateButtonToolTipContinueValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte DefaultUnits {
            get {
                return ((byte)(this["DefaultUnits"]));
            }
            set {
                this["DefaultUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public short SpeedNormal {
            get {
                return ((short)(this["SpeedNormal"]));
            }
            set {
                this["SpeedNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGridLines {
            get {
                return ((bool)(this["ShowGridLines"]));
            }
            set {
                this["ShowGridLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNextFigure {
            get {
                return ((bool)(this["ShowNextFigure"]));
            }
            set {
                this["ShowNextFigure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlaySound {
            get {
                return ((bool)(this["PlaySound"]));
            }
            set {
                this["PlaySound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WithAcceleration {
            get {
                return ((bool)(this["WithAcceleration"]));
            }
            set {
                this["WithAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int SpeedWithAcceleration {
            get {
                return ((int)(this["SpeedWithAcceleration"]));
            }
            set {
                this["SpeedWithAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images/playsound.png")]
        public string PlaySoundImage {
            get {
                return ((string)(this["PlaySoundImage"]));
            }
            set {
                this["PlaySoundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images/mute.png")]
        public string MuteImage {
            get {
                return ((string)(this["MuteImage"]));
            }
            set {
                this["MuteImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press to mute!")]
        public string PlaySoundButtonToolTip {
            get {
                return ((string)(this["PlaySoundButtonToolTip"]));
            }
            set {
                this["PlaySoundButtonToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press to play sound!")]
        public string MuteButtonToolTip {
            get {
                return ((string)(this["MuteButtonToolTip"]));
            }
            set {
                this["MuteButtonToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public short TetrisUnits {
            get {
                return ((short)(this["TetrisUnits"]));
            }
            set {
                this["TetrisUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images/continue.png")]
        public string StateButtonContinueValue {
            get {
                return ((string)(this["StateButtonContinueValue"]));
            }
            set {
                this["StateButtonContinueValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
